listen_port: 8080
algoritm: "least_conn" # или "round_robin"
backends:
  - "http://localhost:8081"
  - "http://localhost:8082"
  - "http://localhost:8083"
health_check:
  interval: "10s"
  timeout: "2s"
  path: "/health"
rate_limiter:
  default_capacity: 100          
  default_rate: "2s"              
  vip_capacity: 300               
  vip_rate: "500ms"               
  db_path: "../data/ratelimit.db"    

