listen_port: 8080
algoritm: "least_conn"
backends:
  - "http://localhost:8081"
  - "http://localhost:8082"
  - "http://localhost:8083"
health_check:
  interval: "10s"
  timeout: "2s"
  path: "/health"
logging:
  level: "info"
  lbfile: "../log/loadbalancer.log"
  dbfile: "../log/database.log"
  rlfile: "../log/ratelimit.log"
rate_limiter:
  default_capacity: 100          
  default_rate: "60s"              
  vip_capacity: 300               
  vip_rate: "20s"               
  db_path: "../data/ratelimit.db"    

